import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { formatDate } from "@/lib/domain/format";

// Mirrors the app's --color-brand / --color-saffron / --color-danger tokens
// (globals.css) as RGB triples, since jsPDF's drawing API takes raw RGB
// rather than CSS variables.
const NAVY: [number, number, number] = [0, 43, 73];
const NAVY_DARK: [number, number, number] = [10, 25, 47];
const SAFFRON: [number, number, number] = [217, 119, 6];
const DANGER: [number, number, number] = [220, 38, 38];
const DANGER_TINT: [number, number, number] = [254, 242, 242];
const WARNING_TINT: [number, number, number] = [255, 247, 237];
const INK: [number, number, number] = [15, 23, 42];
const INK_MUTED: [number, number, number] = [71, 85, 105];
const HAIRLINE: [number, number, number] = [226, 232, 240];
const PAPER_RAISED: [number, number, number] = [255, 255, 255];

export interface ReportKpis {
  totalProjects: number;
  areaAcquiredAcres: number;
  areaNotifiedAcres: number;
  areaAcquiredPercent: number;
  compensationDisbursedCr: number;
  compensationAssessedCr: number;
  compensationPercent: number;
  familiesResettled: number;
  familiesTotal: number;
  resettledPercent: number;
  costOfDelayCr: number;
}

export interface ReportRiskRow {
  title: string;
  state: string;
  daysLeft: number;
}

export interface NationalReportData {
  scopeLabel: string;
  kpis: ReportKpis;
  riskRows: ReportRiskRow[];
}

function inr(n: number) {
  return new Intl.NumberFormat("en-IN").format(Math.round(n));
}

// jsPDF's built-in Helvetica font (WinAnsi encoding) has no glyph for ₹ or ⚠ —
// they render as mojibake ("¹", "&") instead of throwing, so swap in
// government-document-safe ASCII equivalents rather than embedding a custom font.
const RS = "Rs.";


function drawHeader(doc: jsPDF, scopeLabel: string) {
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(...NAVY_DARK);
  doc.rect(0, 0, pageWidth, 32, "F");
  doc.setFillColor(...SAFFRON);
  doc.rect(0, 32, pageWidth, 1.5, "F");

  // Simple seal roundel standing in for the app's GovSeal mark.
  doc.setDrawColor(255, 255, 255);
  doc.setLineWidth(0.8);
  doc.circle(15, 16, 7, "S");
  doc.setFontSize(7);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("GoI", 15, 17.5, { align: "center" });

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...SAFFRON);
  doc.text("ADHIKAR", 27, 12);

  doc.setFontSize(15);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text("National Land Acquisition Report", 27, 20);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(220, 226, 235);
  doc.text("Ministry of Rural Development · Department of Land Resources", 27, 26);

  doc.setFontSize(8);
  doc.setTextColor(220, 226, 235);
  doc.text(`Generated: ${formatDate(new Date())}`, pageWidth - 10, 12, { align: "right" });
  doc.text(`Scope: ${scopeLabel}`, pageWidth - 10, 17, { align: "right" });
}

function drawFooter(doc: jsPDF, pageNumber: number, pageCount: number) {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.setDrawColor(...HAIRLINE);
  doc.setLineWidth(0.3);
  doc.line(10, pageHeight - 14, pageWidth - 10, pageHeight - 14);

  doc.setFontSize(7.5);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(...INK_MUTED);
  doc.text("Confidential — For Official Use Only", 10, pageHeight - 9);

  doc.setFont("helvetica", "normal");
  doc.text("Generated by Adhikar — National Land Acquisition Management System", 10, pageHeight - 5);

  doc.setFont("helvetica", "bold");
  doc.text(`Page ${pageNumber} of ${pageCount}`, pageWidth - 10, pageHeight - 5, { align: "right" });
}

function kpiTile(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  label: string,
  value: string,
  sublabel: string,
  accent: [number, number, number]
) {
  doc.setFillColor(...PAPER_RAISED);
  doc.setDrawColor(...HAIRLINE);
  doc.setLineWidth(0.3);
  doc.roundedRect(x, y, w, h, 1.5, 1.5, "FD");

  doc.setFontSize(7.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...INK_MUTED);
  doc.text(label, x + 4, y + 6);

  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...accent);
  doc.text(value, x + 4, y + h / 2 + 3);

  doc.setFontSize(7.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...INK_MUTED);
  doc.text(sublabel, x + 4, y + h - 4);
}

export function generateNationalReportPdf(data: NationalReportData): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginX = 10;

  drawHeader(doc, data.scopeLabel);

  let y = 42;
  doc.setFontSize(11.5);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...NAVY);
  doc.text("Executive Summary", marginX, y);
  y += 4;

  const gap = 4;
  const tileW = (pageWidth - marginX * 2 - gap) / 2;
  const tileH = 20;
  const row2Y = y + tileH + gap;

  kpiTile(
    doc,
    marginX,
    y,
    tileW,
    tileH,
    "TOTAL PROJECTS",
    inr(data.kpis.totalProjects),
    "Nationwide active records",
    NAVY
  );
  kpiTile(
    doc,
    marginX + tileW + gap,
    y,
    tileW,
    tileH,
    "AREA NOTIFIED VS. ACQUIRED",
    `${inr(data.kpis.areaAcquiredAcres)} / ${inr(data.kpis.areaNotifiedAcres)} acres`,
    `${data.kpis.areaAcquiredPercent}% acquired`,
    NAVY
  );
  kpiTile(
    doc,
    marginX,
    row2Y,
    tileW,
    tileH,
    "COMPENSATION ASSESSED VS. DISBURSED",
    `${RS} ${data.kpis.compensationDisbursedCr.toFixed(1)}Cr / ${RS} ${data.kpis.compensationAssessedCr.toFixed(1)}Cr`,
    `${data.kpis.compensationPercent}% disbursed`,
    [22, 101, 52]
  );
  kpiTile(
    doc,
    marginX + tileW + gap,
    row2Y,
    tileW,
    tileH,
    "FAMILIES AFFECTED VS. RESETTLED",
    `${inr(data.kpis.familiesResettled)} / ${inr(data.kpis.familiesTotal)}`,
    `${data.kpis.resettledPercent}% resettled`,
    SAFFRON
  );

  y = row2Y + tileH + 6;

  // Signature "Cost of Delay" callout — bordered box, same visual weight it
  // carries on the dashboard.
  const calloutH = 24;
  doc.setFillColor(...DANGER_TINT);
  doc.setDrawColor(...DANGER);
  doc.setLineWidth(0.8);
  doc.roundedRect(marginX, y, pageWidth - marginX * 2, calloutH, 2, 2, "FD");

  doc.setFontSize(8.5);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...DANGER);
  doc.text("COST OF DELAY — NATIONAL LOSS", marginX + 5, y + 8);

  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  const costText = `${RS} ${data.kpis.costOfDelayCr.toFixed(2)} Cr`;
  doc.text(costText, marginX + 5, y + 18);
  const costTextWidth = doc.getTextWidth(costText);

  doc.setFontSize(7.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...INK);
  doc.text(
    "Accrued via Section 30(3) 12% & 9%",
    marginX + 10 + costTextWidth,
    y + 15
  );
  doc.text(
    "statutory delay interest on overdue projects",
    marginX + 10 + costTextWidth,
    y + 19.5
  );

  y += calloutH + 8;

  doc.setFontSize(11.5);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...NAVY);
  doc.text("Risk & Compliance Priority List", marginX, y);
  y += 2;

  const body = data.riskRows.map((r) => [
    r.title,
    r.state,
    r.daysLeft < 0 ? `${Math.abs(r.daysLeft)}d overdue` : `${r.daysLeft}d remaining`,
    r.daysLeft < 0 ? "Overdue" : r.daysLeft < 30 ? "Upcoming Deadline" : "On Track",
  ]);

  autoTable(doc, {
    startY: y + 3,
    margin: { left: marginX, right: marginX },
    head: [["Project Name", "State", "Days Overdue / Remaining", "Status"]],
    body,
    theme: "grid",
    styles: { fontSize: 8, cellPadding: 2.2, textColor: INK, lineColor: HAIRLINE, lineWidth: 0.2 },
    headStyles: { fillColor: NAVY, textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    didParseCell: (hookData) => {
      if (hookData.section !== "body") return;
      const row = data.riskRows[hookData.row.index];
      if (!row) return;
      if (row.daysLeft < 0) {
        hookData.cell.styles.fillColor = DANGER_TINT;
        hookData.cell.styles.textColor = DANGER;
      } else if (row.daysLeft < 30) {
        hookData.cell.styles.fillColor = WARNING_TINT;
      }
    },
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    if (i > 1) drawHeader(doc, data.scopeLabel);
    drawFooter(doc, i, pageCount);
  }

  const filenameScope = data.scopeLabel.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  const dateStamp = new Date().toISOString().slice(0, 10);
  doc.save(`adhikar-national-report-${filenameScope}-${dateStamp}.pdf`);
}
